import { Inter } from 'next/font/google'
import Script from 'next/script';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import Header from './components/Header';
import Footer from './components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] })

//Using set title for Page Website
export const metadata = {
  title: '1POS Page',
  description: 'Generated by 1Pos',
}

const idJsonObject = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": "https://tiki.vn/#organization",
  "name": "Tiki",
  "url": "https://tiki.vn/",
  "sameAs": [
    "https://www.facebook.com/tiki.vn/",
    "https://www.instagram.com/Tiki.vn/",
    "https://www.linkedin.com/company/tiki-vn/",
    "https://www.youtube.com/user/TikiVBlog",
    "https://www.tiktok.com/@tiki.official",
    "https://www.pinterest.com/tiki_vn/",
    "https://vi.wikipedia.org/wiki/Tiki"
  ],
  "logo": {
    "@type": "ImageObject",
    "@id": "https://salt.tikicdn.com/cache/w500/ts/upload/c0/8b/46/c3f0dc850dd93bfa7af7ada0cbd75dc0.png/#logo",
    "inLanguage": "vi",
    "url": "https://salt.tikicdn.com/cache/w500/ts/upload/c0/8b/46/c3f0dc850dd93bfa7af7ada0cbd75dc0.png",
    "contentUrl": "https://salt.tikicdn.com/cache/w500/ts/upload/c0/8b/46/c3f0dc850dd93bfa7af7ada0cbd75dc0.png",
    "width": 1080,
    "height": 1080,
    "caption": "Tiki"
  },
  "image": {
    "@id": "https://salt.tikicdn.com/cache/w500/ts/upload/c0/8b/46/c3f0dc850dd93bfa7af7ada0cbd75dc0.png/#logo"
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
        {children}
      <Footer/>
      <Script
         id="my-script"
        type="application/ld+json"
        dangerouslySetInnerHTML={{__html: JSON.stringify(idJsonObject)}}
      />
        </body>
    </html>
  )
}
